enableGlobalCache: true

httpTimeout: 300000

logFilters:
  - code: YN0013
    level: discard

nodeLinker: node-modules

npmRegistryServer: "https://registry.npmjs.org/"

npmScopes:
  arctir:
    npmAlwaysAuth: true
    npmAuthToken: "${GITHUB_TOKEN:-token}"
    npmRegistryServer: "https://npm.pkg.github.com"
